#=============================================================================
# Brief     : Interoperability Test
# Author(s) : Carlos Guimarães <carlos.em.guimaraes@gmail.com>
# ----------------------------------------------------------------------------
# ssTFTP - Open Trivial File Transfer Protocol
#
# Copyright (C) 2008-2023 Carlos Guimarães
#
# This file is part of ssTFTP.
#
# ssTFTP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ssTFTP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ssTFTP. If not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#=============================================================================

name: Interoperability Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  macos:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: mvn clean install

    - name: Run GET and PUT operations with default behavior
      run: |
           sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
           sudo launchctl start com.apple.tftpd
           sudo chmod 777 /private/tftpboot
           sudo touch /private/tftpboot/f1024.txt
           sudo touch /private/tftpboot/f1268.txt
           sudo touch /private/tftpboot/ovos_moles.jpg
           sudo chmod 777 /private/tftpboot/*
           sleep 5

           mv ./example-files/* .
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost
           sleep 5
           
           sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist

    - name: Check results with default behavior
      run: |
           cmp --silent /private/tftpboot/f1024.txt f1024.txt
           cmp --silent /private/tftpboot/f1268.txt f1268.txt
           cmp --silent /private/tftpboot/ovos_moles.jpg ovos_moles.jpg
           rm -rf /private/tftpboot/*

    - name: Run GET and PUT operations with blksize
      run: |
           sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
           sudo launchctl start com.apple.tftpd
           sudo chmod 777 /private/tftpboot
           sudo touch /private/tftpboot/f1024.txt
           sudo touch /private/tftpboot/f1268.txt
           sudo touch /private/tftpboot/ovos_moles.jpg
           sudo chmod 777 /private/tftpboot/*
           sleep 5

           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost -b 512
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost -b 128
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost -b 100
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost -b 100
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost -b 512
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost -b 128
           sleep 5
           
           sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist

    - name: Check results with blksize
      run: |
           cmp --silent /private/tftpboot/f1024.txt f1024.txt
           cmp --silent /private/tftpboot/f1268.txt f1268.txt
           cmp --silent /private/tftpboot/ovos_moles.jpg ovos_moles.jpg
           rm -rf /private/tftpboot/*

    - name: Run GET and PUT operations with tsize
      run: |
           sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
           sudo launchctl start com.apple.tftpd
           sudo chmod 777 /private/tftpboot
           sudo touch /private/tftpboot/f1024.txt
           sudo touch /private/tftpboot/f1268.txt
           sudo touch /private/tftpboot/ovos_moles.jpg
           sudo chmod 777 /private/tftpboot/*
           sleep 5

           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost -s
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost -s
           sleep 5

           sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist

    - name: Check results with interval
      run: |
           cmp --silent /private/tftpboot/f1024.txt f1024.txt
           cmp --silent /private/tftpboot/f1268.txt f1268.txt
           cmp --silent /private/tftpboot/ovos_moles.jpg ovos_moles.jpg
           rm -rf /private/tftpboot/*

    - name: Run GET and PUT operations with interval
      run: |
           sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
           sudo launchctl start com.apple.tftpd
           sudo chmod 777 /private/tftpboot
           sudo touch /private/tftpboot/f1024.txt
           sudo touch /private/tftpboot/f1268.txt
           sudo touch /private/tftpboot/ovos_moles.jpg
           sudo chmod 777 /private/tftpboot/*
           sleep 5

           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost -i 3000
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost -i 3000
           sleep 5

           sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist

    - name: Check results with interval
      run: |
           cmp --silent /private/tftpboot/f1024.txt f1024.txt
           cmp --silent /private/tftpboot/f1268.txt f1268.txt
           cmp --silent /private/tftpboot/ovos_moles.jpg ovos_moles.jpg
           rm -rf /private/tftpboot/*

  ubuntu:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tftpd-hpa

    - name: Build
      run: mvn clean install

    - name: Run GET and PUT operations with default behavior
      run: |
           sudo service tftpd-hpa start
           sudo chmod 777 /srv/tftp/
           sudo touch /srv/tftp/f1024.txt
           sudo touch /srv/tftp/f1268.txt
           sudo touch /srv/tftp/ovos_moles.jpg
           sudo chmod 777 /srv/tftp/*
           sleep 5

           mv ./example-files/* .
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost
           sleep 5

           sudo service tftpd-hpa stop

    - name: Check results with default behavior
      run: |
           cmp --silent /srv/tftp/f1024.txt f1024.txt
           cmp --silent /srv/tftp/f1268.txt f1268.txt
           cmp --silent /srv/tftp/ovos_moles.jpg ovos_moles.jpg
           rm -rf /srv/tftp/*

    - name: Run GET and PUT operations with blksize
      run: |
           sudo service tftpd-hpa start
           sudo chmod 777 /srv/tftp/
           sudo touch /srv/tftp/f1024.txt
           sudo touch /srv/tftp/f1268.txt
           sudo touch /srv/tftp/ovos_moles.jpg
           sudo chmod 777 /srv/tftp/*
           sleep 5

           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost -b 512
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost -b 128
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost -b 100
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost -b 100
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost -b 512
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost -b 128
           sleep 5

           sudo service tftpd-hpa stop

    - name: Check results with blksize
      run: |
           cmp --silent /srv/tftp/f1024.txt f1024.txt
           cmp --silent /srv/tftp/f1268.txt f1268.txt
           cmp --silent /srv/tftp/ovos_moles.jpg ovos_moles.jpg
           rm -rf /srv/tftp/*

    - name: Run GET and PUT operations with tsize
      run: |
           sudo service tftpd-hpa start
           sudo chmod 777 /srv/tftp/
           sudo touch /srv/tftp/f1024.txt
           sudo touch /srv/tftp/f1268.txt
           sudo touch /srv/tftp/ovos_moles.jpg
           sudo chmod 777 /srv/tftp/*
           sleep 5

           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost -s
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost -s
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost -s
           sleep 5

           sudo service tftpd-hpa stop

    - name: Check results with tsize
      run: |
           cmp --silent /srv/tftp/f1024.txt f1024.txt
           cmp --silent /srv/tftp/f1268.txt f1268.txt
           cmp --silent /srv/tftp/ovos_moles.jpg ovos_moles.jpg
           rm -rf /srv/tftp/*

    - name: Run GET and PUT operations with interval
      run: |
           sudo service tftpd-hpa start
           sudo chmod 777 /srv/tftp/
           sudo touch /srv/tftp/f1024.txt
           sudo touch /srv/tftp/f1268.txt
           sudo touch /srv/tftp/ovos_moles.jpg
           sudo chmod 777 /srv/tftp/*
           sleep 5

           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1024.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f f1268.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a put -f ovos_moles.jpg -c localhost -i 3000
           sleep 5

           rm f1024.txt f1268.txt ovos_moles.jpg
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1024.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f f1268.txt -c localhost -i 3000
           sleep 1
           java -jar sstftp-client/target/sstftp-client-0.2.jar -a get -f ovos_moles.jpg -c localhost -i 3000
           sleep 5

           sudo service tftpd-hpa stop

    - name: Check results with interval
      run: |
           cmp --silent /srv/tftp/f1024.txt f1024.txt
           cmp --silent /srv/tftp/f1268.txt f1268.txt
           cmp --silent /srv/tftp/ovos_moles.jpg ovos_moles.jpg
           rm -rf /srv/tftp/*
